sudo: false
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_script:
  - chmod +x ./gradlew

script: ./gradlew clean build

notifications:
  email:
    on_success: change
    on_failure: change